import {
  Bank,
  Binary,
  BracketsCurly,
  Buildings,
  Cake,
  CalendarDots,
  CardsThree,
  ChartLineUp,
  Clock,
  Clover,
  Coins,
  Crosshair,
  FilePdf,
  Fingerprint,
  GasPump,
  Globe,
  Heartbeat,
  HouseLine,
  ImageSquare,
  Keyboard,
  Lightning,
  LockKey,
  MoonStars,
  Percent,
  QrCode,
  Receipt,
  Ruler,
  ShieldCheck,
  ShuffleAngular,
  SquaresFour,
  TextT,
  Timer,
  Wallet,
} from "@phosphor-icons/react/dist/ssr";

const icons = {
  bank: Bank,
  binary: Binary,
  brackets: BracketsCurly,
  buildings: Buildings,
  cake: Cake,
  calendar: CalendarDots,
  cards: CardsThree,
  chart: ChartLineUp,
  clock: Clock,
  clover: Clover,
  coins: Coins,
  crosshair: Crosshair,
  pdf: FilePdf,
  fingerprint: Fingerprint,
  fuel: GasPump,
  globe: Globe,
  heartbeat: Heartbeat,
  house: HouseLine,
  image: ImageSquare,
  keyboard: Keyboard,
  lightning: Lightning,
  lock: LockKey,
  moon: MoonStars,
  percent: Percent,
  qr: QrCode,
  receipt: Receipt,
  ruler: Ruler,
  shield: ShieldCheck,
  shuffle: ShuffleAngular,
  squares: SquaresFour,
  text: TextT,
  timer: Timer,
  wallet: Wallet,
};

export function ToolIcon({ name, large = false }: { name: string; large?: boolean }) {
  const Icon = icons[name as keyof typeof icons] ?? SquaresFour;
  return (
    <span className={`tool-icon${large ? " tool-icon-lg" : ""}`} aria-hidden="true">
      <Icon size={large ? 32 : 22} weight="duotone" />
    </span>
  );
}
